# Generated by Django 3.2.5 on 2021-07-24 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BGDTUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('profile_image_url', models.CharField(max_length=200)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('imageUrl', models.TextField(max_length=200)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usergames', related_query_name='usergame', to='bgdtapi.bgdtuser')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(upload_to='pics/')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versionNumber', models.CharField(max_length=100)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('changes', models.TextField()),
                ('imageUrl', models.TextField(max_length=200)),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameversions', related_query_name='gamesversion', to='bgdtapi.game')),
            ],
        ),
        migrations.CreateModel(
            name='Playtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=100)),
                ('badNotes', models.TextField()),
                ('goodNotes', models.TextField()),
                ('generalNotes', models.TextField()),
                ('playDateTime', models.DateTimeField()),
                ('playerCount', models.IntegerField()),
                ('playtestFeel', models.IntegerField()),
                ('playtestGoals', models.TextField()),
                ('playtestType', models.CharField(max_length=100)),
                ('versionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versionPlaytests', related_query_name='versionPlaytest', to='bgdtapi.version')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=200)),
                ('goodStuff', models.TextField()),
                ('badStuff', models.TextField()),
                ('favoriteFeature', models.TextField()),
                ('enjoyment', models.IntegerField()),
                ('playAgain', models.BooleanField()),
                ('playtestNumber', models.IntegerField()),
                ('playtestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playtestFeedbacks', related_query_name='playtestFeedback', to='bgdtapi.playtest')),
            ],
        ),
    ]
