# Generated by Django 3.2.5 on 2021-07-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgdtapi', '0002_rename_user_id_bgdtuser_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bgdtuser',
            old_name='userid',
            new_name='user_id',
        ),
    ]
