# Generated by Django 3.2.5 on 2021-07-24 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgdtapi', '0003_rename_userid_bgdtuser_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bgdtuser',
            old_name='user_id',
            new_name='user',
        ),
    ]
